version: "3"
services:
        apache:
                image: apache-opencart:latest
                ports:
                        - "4000:80"
                links:
                        - localhost
                environment:
                         hostname: localhost
        localhost:
                image: tutum/mysql
                ports:
                        - "3306:3306"
                environment:
                        MYSQL_ROOT_PASSWORD: rootpassword
                        MYSQL_DATABASE: opencart
                        MYSQL_USER: admin
                        MYSQL_PASSWORD: admin
